const keys = [
  [
    { "key": "esc", "code": "Escape", "keyCode": 27 },
    { "key": "F1", "code": "F1", "keyCode": 0 },
    { "key": "F2", "code": "F2", "keyCode": 0 },
    { "key": "F3", "code": "F3", "keyCode": 0 },
    { "key": "F4", "code": "F4", "keyCode": 0 },
    { "key": "F5", "code": "F5", "keyCode": 0 },
    { "key": "F6", "code": "F6", "keyCode": 0 },
    { "key": "F7", "code": "F7", "keyCode": 0 },
    { "key": "F8", "code": "F8", "keyCode": 0 },
    { "key": "F9", "code": "F9", "keyCode": 0 },
    { "key": "F10", "code": "F10", "keyCode": 0 },
    { "key": "F11", "code": "F11", "keyCode": 0 },
    { "key": "F12", "code": "F12", "keyCode": 0 },
    { "key": "Del", "code": "Delete", "keyCode": 0 },
  ],
  [
    { "key": "`~", "code": "Backquote", "keyCode": 192 },
    { "key": "1!", "code": "Digit1", "keyCode": 49 },
    { "key": "2@", "code": "Digit2", "keyCode": 50 },
    { "key": "3#", "code": "Digit3", "keyCode": 51 },
    { "key": "4$", "code": "Digit4", "keyCode": 52 },
    { "key": "5%", "code": "Digit5", "keyCode": 53 },
    { "key": "6^", "code": "Digit6", "keyCode": 54 },
    { "key": "7&", "code": "Digit7", "keyCode": 55 },
    { "key": "8*", "code": "Digit8", "keyCode": 56 },
    { "key": "9(", "code": "Digit9", "keyCode": 57 },
    { "key": "0)", "code": "Digit0", "keyCode": 48 },
    { "key": "-_", "code": "Minus", "keyCode": 189 },
    { "key": "=+", "code": "Equal", "keyCode": 187 },
    { "key": "←", "code": "Backspace", "keyCode": 8 },
  ],
  [
    { "key": "tab", "code": "Tab", "keyCode": 9 },
    { "key": "Q", "code": "KeyQ", "keyCode": 81 },
    { "key": "W", "code": "KeyW", "keyCode": 87 },
    { "key": "E", "code": "KeyE", "keyCode": 69 },
    { "key": "R", "code": "KeyR", "keyCode": 82 },
    { "key": "T", "code": "KeyT", "keyCode": 84 },
    { "key": "Y", "code": "KeyY", "keyCode": 89 },
    { "key": "U", "code": "KeyU", "keyCode": 85 },
    { "key": "I", "code": "KeyI", "keyCode": 73 },
    { "key": "O", "code": "KeyO", "keyCode": 79 },
    { "key": "P", "code": "KeyP", "keyCode": 80 },
    { "key": "[{", "code": "BracketLeft", "keyCode": 219 },
    { "key": "}]", "code": "BracketRight", "keyCode": 221 },
    { "key": "\\|", "code": "Backslash", "keyCode": 220 },
  ],
  [
    { "key": "caps", "code": "CapsLock", "keyCode": 20 },
    { "key": "A", "code": "KeyA", "keyCode": 65 },
    { "key": "S", "code": "KeyS", "keyCode": 83 },
    { "key": "D", "code": "KeyD", "keyCode": 68 },
    { "key": "F", "code": "KeyF", "keyCode": 70 },
    { "key": "G", "code": "KeyG", "keyCode": 71 },
    { "key": "H", "code": "KeyH", "keyCode": 72 },
    { "key": "J", "code": "KeyJ", "keyCode": 74 },
    { "key": "K", "code": "KeyK", "keyCode": 75 },
    { "key": "L", "code": "KeyL", "keyCode": 76 },
    { "key": ";:", "code": "Semicolon", "keyCode": 186 },
    { "key": "'\"", "code": "Quote", "keyCode": 222 },
    { "key": "←", "code": "Enter", "keyCode": 13 },
  ],
  [
    { "key": "shift", "code": "ShiftLeft", "keyCode": 16 },
    { "key": "Z", "code": "KeyZ", "keyCode": 90 },
    { "key": "X", "code": "KeyX", "keyCode": 88 },
    { "key": "C", "code": "KeyC", "keyCode": 67 },
    { "key": "V", "code": "KeyV", "keyCode": 86 },
    { "key": "B", "code": "KeyB", "keyCode": 66 },
    { "key": "N", "code": "KeyN", "keyCode": 78 },
    { "key": "M", "code": "KeyM", "keyCode": 77 },
    { "key": ",<", "code": "Comma", "keyCode": 188 },
    { "key": ".>", "code": "Period", "keyCode": 190 },
    { "key": "/?", "code": "Slash", "keyCode": 191 },
    { "key": "shift", "code": "ShiftRight", "keyCode": 16 },
    { "key": "↑", "code": "ArrowUp", "keyCode": 38 },
  ],
  [
    { "key": "fn", "code": "Fn", "keyCode": -1 },
    { "key": "ctrl", "code": "ControlLeft", "keyCode": 17 },
    { "key": "alt", "code": "AltLeft", "keyCode": 18 },
    { "key": "cmd", "code": "MetaLeft", "keyCode": 91 },
    { "key": "kumamon", "code": "Space", "keyCode": 32 },
    { "key": "cmd", "code": "MetaRight", "keyCode": 93 },
    { "key": "alt", "code": "AltRight", "keyCode": 18 },
    { "key": "←", "code": "ArrowLeft", "keyCode": 37 },
    { "key": "↓", "code": "ArrowDown", "keyCode": 40 },
    { "key": "→", "code": "ArrowRight", "keyCode": 39 },
  ],
]